### ISSUE TITLE
Laminar flow imperfections

### ISSUE THREAD

**Issue by 0x2b3bfa0** [helpfulengineering/project-georges-cpap#2]
FDM prints have slight imperfections that keep the inner channel's surface from creating a good laminar flow.

**Comment by 0x2b3bfa0** [comment]
This doesn't seem to pose any issue as per the empirical tests done in #1

**Comment by aleksclark** [comment]
This doesn't seem completely solved, in testing the mask produced by #6 I was not able to achieve more than 2cm H2O with air.
see: https://www.youtube.com/watch?v=yGmyCOS2pSA
https://www.youtube.com/watch?v=ehNEK6gB7iQ

**Comment by 0x2b3bfa0** [comment]
Referring to your water test, it looks like a small section of the channel is clogged. Might that affect the performance?
